version: '3'
services:
    php-fpm:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - './:/var/www'
        networks:
            - blog
    nginx:
        image: 'nginx:alpine'
        volumes:
            - './:/var/www'
            - './docker/nginx/conf.d:/etc/nginx/conf.d:ro'
        networks:
            - blog
        ports:
            - '8060:80'
    mysql:
        image: 'mysql:8.1'
        volumes:
            - './docker/mysql:/var/lib/mysql'
        networks:
            - blog
        environment:
            - MYSQL_ROOT_PASSWORD=12345678
        command: '--default-authentication-plugin=mysql_native_password'
    redis:
        image: 'redis:alpine'
        volumes:
            - './docker/redis:/data'
        networks:
            - blog
networks:
    blog:
        driver: bridge
