version: "3.7"

services:
    php:
        container_name: blog-php
        privileged: true
        build:
            context: .
            dockerfile: Dockerfile
            target: laravel
        networks:
            - blog

    nginx:
        container_name: blog-nginx
        build:
            context: .
            dockerfile: Dockerfile
            target: nginx
        privileged: true
        ports:
            - "8080:80"
        networks:
            - blog
        depends_on:
            - php

    mysql:
        container_name: blog-mysql
        image: mysql:8.0
        ports:
            - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: DCYdcy,.?3677
        networks:
            - blog

networks:
    blog:
        driver: bridge
